### ISSUE TITLE
can you tag the 0.3.0 release please?

### ISSUE THREAD

**Issue by mreinstein** [myrne/render-appcache-manifest#6]
``` sh
git clone https://github.com/meryn/render-appcache-manifest.git

render-appcache-manifest

git tag -a 0.3.0 -m "tagging release"

git push origin 0.3.0
```

**Comment by myrne** [comment]
It was already tagged (I use `npm version` command to change package version) but my git client did not push the tags. Other repos of mine may have the same problem.

I've pushed it now. https://github.com/meryn/render-appcache-manifest/releases
